version: "3.9"
services:
  api:
    image: mobyit/planning-poker-api:${TAG}
    ports:
      - 14214:8080
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first
  ui:
    image: mobyit/planning-poker-ui:${TAG}
    ports:
      - 14213:80
    deploy:
      rollback_config:
        failure_action: pause
        monitor: 5s
        parallelism: 1
      restart_policy:
        condition: any
        delay: 3s
      update_config:
        monitor: 5s
        failure_action: rollback
        delay: 5s
        parallelism: 1
        order: stop-first