name: UI
on:
  push:
    branches:
      - "main"
    paths:
      - "ui/**"
      - "e2e/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test ui
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from e2e
  build:
    runs-on: "ubuntu-latest"
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: 'Create env file'
        run: |
          echo "${{ secrets.UI_ENV }}" > ui/.env
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REPOSITORY_NAME }}/planning-poker-ui:${{ github.sha }},${{ secrets.REPOSITORY_NAME }}/planning-poker-ui:latest,
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./ui