name: Build Web
on:
  push:
    branches:
      - "main"
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: web/go.sum
      - name: Test web
        working-directory: ./web
        run: make test
  build:
    runs-on: "ubuntu-latest"
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REPOSITORY_NAME }}/planning-poker-web:${{ github.sha }},${{ secrets.REPOSITORY_NAME }}/planning-poker-web:latest,
          context: ./web