name: Pull Request Test

on:
  pull_request:
    branches:
      - main
jobs:
  test-web:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: web/go.sum
      - name: Test web
        working-directory: web
        run: make test
  test-ui:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test ui
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from e2e